# Generated by Django 3.1.2 on 2022-01-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_user',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Administrador', 'Administrador')], default='Cliente', max_length=50, verbose_name='role'),
        ),
    ]
