# Generated by Django 3.1.2 on 2022-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20220116_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(max_length=400, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
