# Generated by Django 3.1.2 on 2022-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20220121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(null=True, verbose_name='Fecha de cumpleaños'),
        ),
    ]
