# Generated by Django 3.1.2 on 2022-01-24 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_participate_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static\x07ssets\\img', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='idCliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='idProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='idCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='idEmployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
    ]
