# Generated by Django 3.1.2 on 2022-01-28 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0009_auto_20220124_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['startDate'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterField(
            model_name='participate',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.user', verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='idProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.project', verbose_name='id'),
        ),
    ]
