# Generated by Django 3.1.2 on 2022-02-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0011_auto_20220202_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registerDate',
            field=models.DateTimeField(null=True, verbose_name='Fecha de registro'),
        ),
    ]
